### ISSUE TITLE
Feature request: consider library extraction

### ISSUE THREAD

**Issue by dkgitdev** [essential61/mp4analyser#32]
Hi! I've ran across this tool and thought that it'll be great to separate Tk app and MP4 parsing library as some other PyPI package

**Comment by essential61** [comment]
Hi Dmitry,
I think I want to keep this repo as a complete application as, I imagine, most people just want to download something that just works straight away.

I have structured the application so that all the GUI elements are in a single file, mp4analyser.py so if you just want the parsing library you can simply delete this file.

I am also happy for anyone to fork this repo, create a library on pypi or whatever to suit their needs.
